# Generated by Django 5.2.9 on 2025-12-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_threshold', models.FloatField(default=0.5, help_text='Minimum confidence for detecting a face (0.0 - 1.0)')),
                ('grouping_threshold', models.FloatField(default=0.45, help_text='Minimum similarity to group faces together (0.0 - 1.0)')),
                ('min_face_size', models.IntegerField(default=80, help_text='Minimum face height/width in pixels')),
                ('frame_skip_extract', models.IntegerField(default=10, help_text='Process every Nth frame for extraction')),
                ('frame_skip_group', models.IntegerField(default=5, help_text='Process every Nth extracted face for grouping')),
                ('gpu_enabled', models.BooleanField(default=True, help_text='Attempt to use GPU if available')),
            ],
        ),
        migrations.CreateModel(
            name='FaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(help_text='Folder name e.g. celebrity_001', max_length=50)),
                ('face_count', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0, help_text='Average similarity score of faces in this group')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (High Confidence)'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk (Low Confidence)')], default='HIGH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_groups', to='core.movie')),
            ],
            options={
                'ordering': ['movie', 'group_id'],
                'unique_together': {('movie', 'group_id')},
            },
        ),
    ]
