# Generated by Django 5.2.9 on 2025-12-26 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facerecognitionsettings_facegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='facegroup',
            name='avg_quality',
            field=models.FloatField(default=0.0, help_text='Average quality score of faces in this group'),
        ),
        migrations.AddField(
            model_name='facegroup',
            name='is_labeled',
            field=models.BooleanField(default=False, help_text='Whether this group has been labeled with an identity'),
        ),
        migrations.AddField(
            model_name='facegroup',
            name='name',
            field=models.CharField(blank=True, help_text='Optional assigned name (actor name)', max_length=255),
        ),
        migrations.AddField(
            model_name='facegroup',
            name='representative_embedding',
            field=models.BinaryField(blank=True, help_text='Serialized representative embedding(s)', null=True),
        ),
        migrations.AddField(
            model_name='facegroup',
            name='total_faces',
            field=models.IntegerField(default=0, help_text='Total number of faces in this group'),
        ),
        migrations.CreateModel(
            name='FaceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.CharField(help_text='Path to source image or video frame', max_length=500)),
                ('frame_number', models.IntegerField(blank=True, help_text='Frame number if from video', null=True)),
                ('bbox', models.JSONField(default=list, help_text='Bounding box [x1, y1, x2, y2]')),
                ('embedding', models.BinaryField(blank=True, help_text='512-D ArcFace embedding', null=True)),
                ('quality_score', models.FloatField(default=0.0, help_text='Combined quality score (0.0-1.0)')),
                ('blur_score', models.FloatField(default=0.0, help_text='Blur score from Laplacian variance')),
                ('illumination_score', models.FloatField(default=0.0, help_text='Illumination score from brightness analysis')),
                ('pose_score', models.FloatField(default=0.0, help_text='Pose score from landmark symmetry')),
                ('detection_confidence', models.FloatField(default=0.0, help_text='Detection model confidence')),
                ('image_hash', models.CharField(blank=True, help_text='Perceptual hash (pHash)', max_length=64)),
                ('is_valid', models.BooleanField(default=True, help_text='Passes quality thresholds')),
                ('is_outlier', models.BooleanField(default=False, help_text='Marked as outlier from group')),
                ('yaw', models.FloatField(blank=True, help_text='Horizontal rotation in degrees', null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Vertical rotation in degrees', null=True)),
                ('roll', models.FloatField(blank=True, help_text='In-plane rotation in degrees', null=True)),
                ('cropped_image_path', models.CharField(blank=True, help_text='Path to saved cropped face', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='core.facegroup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image_hash'], name='core_facede_image_h_a6f043_idx'), models.Index(fields=['is_valid', 'is_outlier'], name='core_facede_is_vali_a278c0_idx'), models.Index(fields=['face_group'], name='core_facede_face_gr_c27b8d_idx')],
            },
        ),
    ]
