# Generated by Django 5.2.9 on 2025-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facegroup_avg_quality_facegroup_is_labeled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facerecognitionsettings',
            name='quality_threshold',
            field=models.FloatField(default=0.5, help_text='Minimum combined quality score to keep a face'),
        ),
        migrations.AddField(
            model_name='facerecognitionsettings',
            name='redundancy_threshold',
            field=models.FloatField(default=0.85, help_text='Embedding similarity above this = too similar, skip'),
        ),
    ]
